- name: Deploy Docker Container
  hosts: all
  # this defines which hosts (machines) the tasks in this playbook will be applied to.
  # all refers to all hosts listed in the inventory file. In your inventory, this is likely pointing to localhost or any other machine.
  become: yes #This ensures that the tasks will be executed with elevated privileges (like sudo on Linux
  tasks:
    - name: Ensure Docker is Installed
      apt: #Ansible to use the apt package manager
        name: docker.io
        state: present #ensures that the Docker package is installed. If Docker is not installed, Ansible will install it.
      when: ansible_os_family == "Debian" #task only runs if the operating system on the target machine is Debian-based (such as Ubuntu).

    - name: Pull Docker image
      community.docker.docker_image:
        name: aaradhyaghota/calculator
        tag: latest
        source: pull

    - name: Stop and remove existing container (If running)
      community.docker.docker_container:
        name: calculator
        state: absent
        force_kill: yes

    - name: Run the new container
      community.docker.docker_container:
        name: calculator
        image: aaradhyaghota/calculator:latest
        state: started
        restart_policy: always
        ports:
          - "9090:8080"
        interactive: yes
        tty: yes